format_version: 4
environments:
  gcp:
    environment_variables:
      GCLOUD_CLUSTER: devops-workshop-gke
      GCLOUD_ZONE: us-central1-a
      GCLOUD_PROJECT_ID: devops-workshop-123
    secure_variables:
      GCLOUD_SERVICE_KEY: AES:LEHXbZaCcJ0ZNoWNPVG+Gg==:ES5uadachA+0dzVSCDibx1VS7fm/oxV0+rDx4uTltO6fcbh3FSpuumix6f8dTdC0mDo/hFdD3e60EW0G9SK1yDP6Oo5OR5XiajW6y6yVWZKyW3FdvoFcHiV26KwQNDcfkASoeN35tIAfOnefZG51g/i5KKms30d2vCzY+hWvtV0zCc0lFz+XTno80vgfvSTQkvRSl6ABQuKsWNCtwrH4FDHff1bK2tSBa4YbIs7n5mU92JR4rXlFreZJrrW4sbFh5w3gFksKmRtUOUz4SBb0FwSHgsp9AtAKD3dCndYw4+a65svV4t9Hsa36stCL4RQGcK8O3gObOEKInCHa6mhiUhCpH1Sh5XKciuVYYMsJa2oK8a0KW3hN2KoFYXGFZdk+u7fNVJxy7glnH8N4W78pMGEBhBwcV6x81O2dsh83JpCwrE8pSgqy2t4zefcP1iJCf2nlMW0fb7e9ol8/ceUSPTxNHU0Wn9Je1BzkMuEHbVFmrI6zeEMVUGxIrrqydKAtfetFPXXlx3y04D44KmV7BMYtTC14N1cZu1NXeXWHeIA48U/dMe1wU7x4SHKeV1s5FJ9TpY3yFZwunLNHIwjpHGIj7feBRDgdoQt2wSCktyG20cWoxcnyMzXf/+1OtXylR2PkqOReMW+22gZyt5lU+V7Ee+FLe0TAoTfujottvKKiXqqGtCf1ZhDSynq5TgUMkndqMgdJxpXZxv/qx+P0PANfoxkLNv7KO++q0Ngwi7yP+vcXWZ9VZO1WVbnZma+VpipLNxmrhIjvo8luhuURZcxzMpMDl95ZTmx+HGB9meUd+ESNEep9o4zwD7RlvV125Aeg5qc/hNqsB593yyjMpEFM+wTA2oI48tjF74x/hLyaZoQnZFe8J+odcfovynYRZ4mnXPtZUaWD/3M8LaYVkc8rzLBoLKemdwvM4lsTPStqYTY15YHlQuVIY8OkzLu8RvNJsYr1OkAhbJ2BlfSQKF7069RU/8BCJC1wyiRju2HPhIhm5rD31hYDf91NWEKjDsOWdZOsDe2Y3qpTFPmL9eyttSKvx5oal8N5PVm9HcKcvdX02t4N64rzphQh5mhqglB4/Wt5FMJmE0+I7BEhAfQiHD/OdBZiaHM9I1Go/0XSOSwW/sMeT0DHE0xiPj73mHFJrQi4JoUTxF2rAtJFeBBTqIE3RHXVNsKNU5LvtJF+EPiW9RzjLhzsLdVOP90yEC5gZWwfp/pQGYDmN+Nh3HMDsgEqSeaYwukA2Q6lTbEnreMkHAPj0nTr2NHlNzcdRGEPv1XXeAT+5p7oVLvSeQiPuVTyVyce85jQjfMq/nHi3M+g0C+p7/DkFDnRuzzGNH0+Uv6mdOI2jhJxT6/qjxrF9RhvYYEdVimOw6IhPOTD1BgnkVfpal2FWt4G9CqDSkRAuwkMlCe0MGqw3iETkSQe6V54O3LJGOqT3dAM2a0jUX6/o4Pf0Q7Zi8F0grk4+uiuMp69j48XyPu/lXZDmv1nY3cJLm7Af+2Qkw9YhQbY03xegqTqpAXJaActOJPyOHHJU6yY9N1TUwstWWBK1D9G5G+r20YYEz1Kel62o43W0hXiRp3j6zgdkZerqpz26c98gz2Ey5RZWnYvw2k6UKOmZ+1MjdA7LxEj6uPrnf+6HPARB/lVAOG5uekUrp2ZA4X74v2jMECdqDgua09iRsUHUCQ4eodXWLLHdRv8/bp3vgNx3lpgIrUg8ptBcXdpDWarwBllYWJzg63rfzZ14wN/ui2G6Pb0R2OBGL+itjCMhRXtrbNsm+yehiJwbFZlsivgA7Y4Ks/GMcPrjEjNDhegFE9EOxoNRZ3TMKtzaovSIkygwRHh9423fxuOVipAZYAzvEGbIrhC7vOAlflBXZ7Ebynajx2xzs9zkOQYpSjR/YAEi68qZYfHZw/T4000VcYyYtr8lm53nqFEqIZ/MVVvWsPIXEnlxMu6ObjZDdPaicz5gIAArTcjF0vQ4vDzNcrYMzvmRYEqdt7TwS2aQdLpwe6UVtYlZ+SBjviwDTnWHKOoBPYvHUxJl5RZHTjC0gjwnGaSBoxqvo9q0YAbdVFzzQo2bwKcU8xlUnUjXHGCh2Lzhnq8zi+A/6KZGkPEK9S7Ws1QiWFV3u7gDJH078vSb66ax2ZE0jE7e4GM+KbXykm/imC8hUpAQTrZD/83o9P/IOm+a8NtbeBxm8c/J5DWzl88AnKHyZIbynQEvM2jCBQHn/zHrRDYvLsoSbIqg80SQbXuuCazQqjEWUz2TCyLSRSGFbI4vYTREG89gvkUsuDJQcVNTLgBsT37WYI/Mj4+XG9Mc4l4zaUBq8NccgQX5mwBu0AFKS50P15F/MxTXC6zRNX3essH/StsUhiyxqmc3F0+9lTn/VOpZabaOP0vHKF9W86Fw21Z1zICEGPgViQg4I0LqEpaZx6soeRI2Jw4mPFyQm4KC5k3w3X8xX2n7gMZ6d+dEaCu1iFgbleCogte7jTCYrr2sHhxUDUEY7pZAn0Ax+KZSV5brZFBRKvriTDrcL3Qv+/P9XG0N2KMYy4NnzMkEJB/rC5oLKUBfKV7oX8GOIE6MDbcCT02z6w4GqiqxCEpE8f7zvtQtfQTY9PI+X4AdTyFWLmVpniD2ia2ecYbOxkOj+JzqZ0xjKBbmTxOaDncbb5vwbncI5PuV1cO/utrcQsLIGwjeDWdkdnvRbYdgjGalH/JQAjLSwb4+5bjQXu7IasKjXPswM5hKwXQ2hztBdUiISaWzP8t+r51feLrUqC/AqQbURTVESOb2c971yhm5M+aQrlo6co4RrYK+cnW/7SJi8ZKzerdv55Fk/mQIPVRbpv9YfkH+HUOky/rgWsImIDfrSx0/aIGO4Jt+ES8S4jX1tgBcuXqxhqdg6funa+hT3Iz+ICR9EXmPuxLW8f6q4n7Fn0REt8c+L1hLr3mnL3z7Zh5yI3IasF10WzjrD2XGt3zbGKhXrA+tzAlgDJmafHQy0InJ3dxoAADpzIE7xI7NVy1mTA0AnlflKBpnP0RWmNcdeJ1GH8nPmSrUMBAAQaGf1i9o0/iiVDZOGADzzFmVIkhVAFuxfrVFJOt0m0jHhljJ5BX9Vqimrqge3sDm5EpMgKIayHctbjnMlE4+5Al29ZAcr036PBSi2Oh4qwgBp16NiLxEG88Dwy33WY1q2MOr7Ipxf/exXyxeEL0krIDR3WXPrbiOcsbNIgZbroOfA0Ikvv3iPZTEBvFe5O6PoWMJp/ZnyWpHDgh91OGuH8PZGyXT1rdJKkFR1uEsy3IDmCq2iuBBmfTpdlmV4OGIYdqDXzyXFAGNF0T4ZzoMbpNcREC9N3RypOaSGZm5y7oOTzq2QPObWQTViZGHLYOkwTcTaHVjxZC7C3WyxPCans7JEOB+1sGusQLtBVXEacWWzQQh4ZLvrew2xGW4MoASUZO7p8XvIpygWyjPLyRYK5atuExxh/+19y8SeVM7uvnPgBPyaKbfb6MJzspQ9USoICCPNmPTSmSuzlN6Uc8iiHq93nR/esXesWuUAwm5eXylPYUxcY+BmRTOnXULhQI1D7PHiT17XP+m+e9n5lmcSRMjIbp4Ti7/ypeDZoeAlfq5ph43kqsQ2jMRKkiJf8NTCXFWayG8gysXmTCa6/eGIlYo/QhkhmMP/n8mVZuX/lbR5KqwzFtt96ilpHy9GCcvZ1aWoNP9BXOJ1n0xE6iIRQKZVYHZ8xdqHnHTUQYsgc87iad8qrgkE54myjjFxDOFAur8B8sFOlenNBuxi9U6RDkfn6x1buxQhZENl8OBIKd8BfIfhl9xBElM4EzuQ3HByOVjMMdxUJzGmGl7OAg0+1y59uoadf1toMIGZ73VN2IIvfAmMOO5cFGSGZ8KQg5pASaVaqyeXECO7PgjBNmg97EfFYcgfgJOGfyvnbgXjn7KdVi+fJnj7iMAjwxWwSt7RjPg+j7sWp4E6dLuwCHBbIvsZIue4xp4a6UT8mLzOGvfu2Vb5/VTIgrg29ih6MK+M52WgqQ1r1GJvY9Ph0Vi1DgoqCo9/JI0oaxNN320UW0UuLwYEkAfD0v1bbsIvrpFktyUjNEkb3OcKzt1iNYbS7egXSDoH6iAOB3mfH4LOAVqRhImb3LkQacAD44MUzI8ay1Q//vvNFbAv/pdXA7YiFM33TI6Sao
    pipelines:
      - PetClinic
pipelines:
  PetClinic:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/dtsato/devops-in-practice-workshop.git
        shallow_clone: false
        auto_update: true
        branch: tw-may-19
    stages:
    - commit:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build-and-publish:
            timeout: 0
            environment_variables:
              MAVEN_OPTS: -Xmx1024m
            elastic_profile_id: docker-jdk
            artifacts:
              - test:
                  source: target/surefire-reports
            tasks:
            - exec:
                arguments:
                - clean package
                command: ./mvnw
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker build --tag pet-app:$GO_PIPELINE_LABEL --build-arg JAR_FILE=target/spring-petclinic-2.0.0.BUILD-SNAPSHOT.jar .
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker login -u _json_key -p"$(echo $GCLOUD_SERVICE_KEY | base64 -d)" https://us.gcr.io
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker tag pet-app:$GO_PIPELINE_LABEL us.gcr.io/$GCLOUD_PROJECT_ID/pet-app:$GO_PIPELINE_LABEL
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker push us.gcr.io/$GCLOUD_PROJECT_ID/pet-app:$GO_PIPELINE_LABEL
                command: bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: kubectl
            tasks:
            - exec:
                arguments:
                - -c
                - echo $GCLOUD_SERVICE_KEY | base64 -d > secret.json && chmod 600 secret.json
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - gcloud auth activate-service-account --key-file secret.json
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT_ID
                command: bash
                run_if: passed
            - exec:
                command: ./deploy.sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - rm secret.json
                command: bash
                run_if: passed
